version: "3.8"

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

# Frontend em Angular
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 4200:4200
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: "npm run -- ng serve --host 0.0.0.0 --disable-host-check"